# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: package-release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events for all new tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: install packages
        run: rm bun.lock && bun install

      - name: build package
        run: bun run build

      - name: publish release
        run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
